/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */
import type { String } from './string';

export interface Fiat {
  id: String;
  symbol: string;
}
