/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */

export type GetAssetsChartParams = {
/**
 * Chart start timestamp (unix seconds).
 */
startPeriod: number;
/**
 * Chart end timestamp (unix seconds).
 */
endPeriod: number;
};
