/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */
import type { ImportPortfolioBodyAssetsItemAclass } from './importPortfolioBodyAssetsItemAclass';
import type { ImportPortfolioBodyAssetsItemFees } from './importPortfolioBodyAssetsItemFees';
import type { ImportPortfolioBodyAssetsItemProvider } from './importPortfolioBodyAssetsItemProvider';

/**
 * Portfolio asset
 */
export type ImportPortfolioBodyAssetsItem = {
  /** Asset class */
  aclass: ImportPortfolioBodyAssetsItemAclass;
  /**
     * Asset base currency
     * @minLength 1
     */
  baseCcy: string;
  /** Transaction fees */
  fees?: ImportPortfolioBodyAssetsItemFees;
  /**
     * Asset name
     * @minLength 1
     */
  name: string;
  /**
     * Asset price
     * @pattern ^[0-9]+(?:\.[0-9]+)?$
     */
  price: string;
  /** Price provider (choose DCAPal for Crypto, YF for anything else) */
  provider: ImportPortfolioBodyAssetsItemProvider;
  /**
     * Number of units of the asset in portfolio
     * @pattern ^[0-9]+(?:\.[0-9]+)?$
     */
  qty: string;
  /**
     * Asset ticker
     * @minLength 1
     */
  symbol: string;
  /**
     * Asset target weight
     * @pattern ^[0-9]+(?:\.[0-9]+)?$
     */
  targetWeight: string;
};
