/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */

/**
 * Price provider (choose DCAPal for Crypto, YF for anything else)
 */
export type ImportPortfolioBodyAssetsItemProvider = typeof ImportPortfolioBodyAssetsItemProvider[keyof typeof ImportPortfolioBodyAssetsItemProvider];


export const ImportPortfolioBodyAssetsItemProvider = {
  DCAPal: 'DCAPal',
  YF: 'YF',
} as const;
