/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */

/**
 * Fee structure
 */
export type ImportPortfolioBodyFeesFeeStructure = {
  type: 'zeroFee';
} | {
  /**
     * Transaction fee amount
     * @pattern ^[0-9]+(?:\.[0-9]+)?$
     */
  feeAmount: string;
  type: 'fixed';
} | {
  /**
     * Decimal percentage represented as a string
     * @pattern ^[0-9]+(?:\.[0-9]+)?$
     */
  feeRate: string;
  /**
     * Transaction fee maximum amount
     * @pattern ^[0-9]+(?:\.[0-9]+)?$
     */
  maxFee?: string;
  /**
     * Transaction fee minimum amount
     * @pattern ^[0-9]+(?:\.[0-9]+)?$
     */
  minFee: string;
  type: 'variable';
};
