/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */

/**
 * Provider matching is case-insensitive; DCAPal and Kraken map to Kraken, while YF and Yahoo map to YF.
 */
export type PortfolioAssetRequestProvider = typeof PortfolioAssetRequestProvider[keyof typeof PortfolioAssetRequestProvider];


export const PortfolioAssetRequestProvider = {
  DCAPal: 'DCAPal',
  Kraken: 'Kraken',
  YF: 'YF',
  Yahoo: 'Yahoo',
} as const;
