/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */

/**
 * Canonical v1 Asset Class name. Cash and Currency are returned as CURRENCY.
 */
export type PortfolioAssetResponseAclass = typeof PortfolioAssetResponseAclass[keyof typeof PortfolioAssetResponseAclass];


export const PortfolioAssetResponseAclass = {
  EQUITY: 'EQUITY',
  BOND: 'BOND',
  CURRENCY: 'CURRENCY',
  CRYPTO: 'CRYPTO',
  COMMODITY: 'COMMODITY',
  OTHER: 'OTHER',
} as const;
