/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */
import type { TransactionFeesResponse } from './transactionFeesResponse';

/**
 * An asset held by a portfolio.
 *
 * Decimal values are serialized as JSON strings to preserve precision.
 */
export interface PortfolioAssetResponse {
  /** The asset class. */
  aclass: string;
  /** The average price paid for the holding. */
  averageBuyPrice: string;
  /** The asset currency. */
  baseCcy: string;
  fees?: null | TransactionFeesResponse;
  /** The asset display name. */
  name: string;
  /** The latest known price. */
  price: string;
  /** The data provider for the asset. */
  provider: string;
  /** The quantity held. */
  qty: string;
  /** The provider symbol for the asset. */
  symbol: string;
  /** The target portfolio weight. */
  targetWeight: string;
}
