/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */
import type { PortfolioResponse } from './portfolioResponse';

/**
 * Server changes returned after portfolio synchronization.
 */
export interface SyncPortfoliosResponse {
  deletedPortfolios: string[];
  updatedPortfolios: PortfolioResponse[];
}
