/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */
import type { PortfolioResponse } from './portfolioResponse';

/**
 * The result of synchronizing the client's portfolio set.
 */
export interface SyncPortfoliosResponse {
  /** Portfolio identifiers that the client should remove. */
  deletedPortfolios: string[];
  /** Portfolios whose server state should be applied by the client. */
  updatedPortfolios: PortfolioResponse[];
}
