/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */
import type { FeeStructure } from './feeStructure';

/**
 * Transaction fee settings returned by the API.
 */
export interface TransactionFeesResponse {
  /** The fee calculation model. */
  feeStructure: FeeStructure;
  /**
     * The maximum allowed fee impact, when configured.
     * @nullable
     */
  maxFeeImpact?: string | null;
}
