/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */

export interface YahooSearchQuote {
  /** @nullable */
  exchange?: string | null;
  /** @nullable */
  longname?: string | null;
  /** @nullable */
  quoteType?: string | null;
  /** @nullable */
  shortname?: string | null;
  /** @nullable */
  symbol?: string | null;
}
