app:
  providers:
    priceProvider: yahoo
    cwApiKey: CW_API_KEY
    ipApiKey: IP_API_KEY
    # cmcApiKey: CMC_API_KEY
  auth:
    jwtSecret: SUPABASE_JWT_SECRET

  # services:
  #   ip:
  #     dbPath: PATH_TO_IP2LOCATION_BIN

  log:
    level: dcapal_backend=info,tower_http=debug
    file: dcapal.log
    enableStdout: true

server:
  web:
    hostname: 127.0.0.1
    port: 8080
  metrics:
    hostname: 127.0.0.1
    port: 9000
  redis:
    hostname: 127.0.0.1
    port: 6379
    user: dcapal
    password: dcapal
  postgres:
    hostname: supabase_db_dcapal
    port: 5432
    user: postgres
    password: postgres
    database: postgres
