app:
  providers:
    priceProvider: @@DCAPAL_PRICE_PROVIDER@@
    cwApiKey: @@DCAPAL_CW_API_KEY@@
    ipApiKey: @@DCAPAL_IP_API_KEY@@
    cmcApiKey: @@DCAPAL_CMC_API_KEY@@
  auth:
    jwtSecret: @@DCAPAL_JWT_SECRET@@
    jwtJwks: @@DCAPAL_JWT_JWKS@@

  services: @@DCAPAL_SERVICES@@

  log:
    level: @@DCAPAL_LOG_LEVEL@@
    file: @@DCAPAL_LOG_FILE@@
    enableStdout: @@DCAPAL_LOG_ENABLE_STDOUT@@

server:
  web:
    hostname: @@DCAPAL_WEB_HOSTNAME@@
    port: @@DCAPAL_WEB_PORT@@
  metrics:
    hostname: @@DCAPAL_METRICS_HOSTNAME@@
    port: @@DCAPAL_METRICS_PORT@@
  redis:
    hostname: @@DCAPAL_REDIS_HOSTNAME@@
    port: @@DCAPAL_REDIS_PORT@@
    user: @@DCAPAL_REDIS_USER@@
    password: @@DCAPAL_REDIS_PASSWORD@@
  postgres:
    hostname: @@DCAPAL_POSTGRES_HOSTNAME@@
    port: @@DCAPAL_POSTGRES_PORT@@
    user: @@DCAPAL_POSTGRES_USER@@
    password: @@DCAPAL_POSTGRES_PASSWORD@@
    database: @@DCAPAL_POSTGRES_DATABASE@@
