# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
   # Enable version updates for cargo
  - package-ecosystem: "cargo"
    directory: "/dcapal-backend"
    schedule:
      interval: "weekly"

   # Enable version updates for cargo
  - package-ecosystem: "cargo" 
    directory: "/dcapal-optimizer-wasm"
    schedule:
      interval: "weekly"

   # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/dcapal-frontend"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/dcapal-backend/docker"
    # Check for updates once a week
    schedule:
      interval: "weekly"
