# Enables nightly-only features
unstable_features = true

# General style
edition = "2024"

# Import organization
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
reorder_modules = true

# Comment and doc style
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true