-- USERS
create table public.users
(
    id         uuid                                   not null primary key,
    username   text,
    email      text                                   not null unique,
    role       text                                   not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

-- ROLES
-- create table public.roles
-- (
--     id         bigint generated by default as identity primary key,
--     name       text                                   not null,
--     status     text                                   not null,
--     created_at timestamp with time zone default now() not null,
--     updated_at timestamp with time zone default now() not null
-- );

-- USER ROLES
-- create table public.user_roles
-- (
--     id         bigint generated by default as identity primary key,
--     user_id    uuid references public.users on delete cascade not null,
--     role_id    bigint references public.roles                 not null,
--     created_at timestamp with time zone default now()         not null,
--     updated_at timestamp with time zone default now()         not null,
--     unique (user_id, role_id)
-- );
--
-- -- PERMISSIONS
-- create table public.permissions
-- (
--     id         bigint generated by default as identity primary key,
--     name       text                                   not null unique,
--     created_at timestamp with time zone default now() not null,
--     updated_at timestamp with time zone default now() not null
-- );

-- ROLE PERMISSIONS
-- create table public.role_permissions
-- (
--     id            bigint generated by default as identity primary key,
--     role_id       bigint references public.roles         not null,
--     permission_id bigint references public.permissions   not null,
--     created_at    timestamp with time zone default now() not null,
--     updated_at    timestamp with time zone default now() not null,
--     unique (role_id, permission_id)
-- );

-- PORTFOLIOS
create table public.portfolios
(
    id              uuid primary key         default gen_random_uuid(),
    user_id         uuid references public.users           not null,
    name            text                                   not null,
    currency        text                                   not null,
    deleted         boolean                                not null default false,
    last_updated_at timestamp with time zone default now() not null,
    max_fee_impact  numeric(20, 10)                        null,
    fee_type        text                                   null,
    fee_amount      numeric(20, 10)                        null,
    fee_rate        numeric(20, 10)                        null,
    min_fee         numeric(20, 10)                        null,
    max_fee         numeric(20, 10)                        null,
    created_at      timestamp with time zone default now() not null,
    updated_at      timestamp with time zone default now() not null
);

-- ASSETS
-- create table public.assets
-- (
--     id          uuid primary key         default gen_random_uuid(),
--     symbol      text                                   not null unique,
--     name        text                                   not null,
--     asset_class text                                   not null,
--     currency    text                                   not null,
--     provider    text                                   not null,
--     created_at  timestamp with time zone default now() not null,
--     updated_at  timestamp with time zone default now() not null,
--     unique (symbol)
-- );

-- PORTFOLIO ASSETS
create table public.portfolio_asset
(
    id             uuid primary key         default gen_random_uuid(),
    symbol         text                                   not null,
    portfolio_id   uuid references public.portfolios      not null,
    name           text                                   not null,
    asset_class    text                                   not null,
    currency       text                                   not null,
    provider       text                                   not null,
    quantity       numeric(20, 10)                        not null,
    target_weight  numeric(20, 10)                        not null,
    price          numeric(20, 10)                        not null,
    max_fee_impact numeric(20, 10)                        null,
    fee_type       text                                   null,
    fee_amount     numeric(20, 10)                        null,
    fee_rate       numeric(20, 10)                        null,
    min_fee        numeric(20, 10)                        null,
    max_fee        numeric(20, 10)                        null,
    created_at     timestamp with time zone default now() not null,
    updated_at     timestamp with time zone default now() not null
);

-- ASSET PRICES
-- create table public.asset_prices
-- (
--     id            uuid primary key         default gen_random_uuid(),
--     instrument_id uuid references public.assets          not null,
--     eod_price     numeric(20, 10)                        not null,
--     date          date                                   not null,
--     created_at    timestamp with time zone default now() not null,
--     updated_at    timestamp with time zone default now() not null
-- );
