name: 🚀 Enhancement Request
description: For issues related to application improvements.
title: "[Enhancement]: "
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, check existing [issues](https://github.com/leonardoarcari/dcapal/issues) and upvote if applicable.
  - type: textarea
    attributes:
      label: Is your enhancement request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "It can be solved in this way ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "I expect to receive my portfolio but ..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "In addition my browser crash."
    validations:
      required: false
