services:
  redis:
    volumes:
      - ./data/redis:/data

  dcapal:
    image: ${DCAPAL_IMAGE:-leonardoarcari/dcapal:latest}
    env_file: ${DCAPAL_ENV_FILE:-dcapal.env}
    restart: always
    ports:
      - "${DCAPAL_API_PORT:-8080}:8080"
      - "${DCAPAL_METRICS_PORT:-9000}:9000"
    networks:
      - ${DCAPAL_NETWORK:-dcapalnetwork}
    volumes:
      - ./dcapal.yml:/var/dcapal/dcapal-backend/dcapal.yml
      - ./data/dcapal:/var/dcapal/dcapal-backend/data
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
