services:
  redis:
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  db:
    ports:
      - "${POSTGRES_HOST_PORT:-5433}:5432"
    volumes:
      - db_data:/home/postgres/pgdata/data
      - ./config/db/init:/docker-entrypoint-initdb.d:ro

volumes:
  db_data:
  redis_data:
