version: "3.9"
services:
  redis:
    image: redis/redis-stack-server:7.2.0-v0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - dcapalnetwork
    volumes:
      - ./config/redis/redis-stack.conf:/redis-stack.conf
      - ./config/redis/users.acl:/etc/redis/users.acl
      - ./data/redis/:/data
    healthcheck:
      test: redis-cli --raw ping
      interval: 10s
      timeout: 10s
      retries: 3
  postgres:
    container_name: supabase-db
    image: supabase/postgres:15.1.1.78
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # prevents Realtime polling queries from appearing in logs
    restart: 'no'
    ports:
      # Pass down internal port because it's set dynamically by other services
      - "5432:5432"
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: 5432
      POSTGRES_PORT: 5432
      PGPASSWORD: postgres
      POSTGRES_PASSWORD: postgres
      PGDATABASE: postgres
      POSTGRES_DB: postgres

networks:
  dcapalnetwork:

volumes:
  db-config: