version: "3.9"
services:
  redis:
    image: redis/redis-stack-server:7.2.0-v0
    container_name: redis
    restart: always
    ports:
      - 50125:6379
    networks:
      - dcapalnetwork
    volumes:
      - ./config/redis/redis-stack.conf:/redis-stack.conf
      - ./config/redis/users.acl:/etc/redis/users.acl
      - ./data/redis/:/data
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  dcapalnetwork: