version: "3.9"
services:
  redis:
    image: redis/redis-stack-server:7.2.0-v0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - dcapalnetwork
    volumes:
      - ./config/redis/redis-stack.conf:/redis-stack.conf
      - ./config/redis/users.acl:/etc/redis/users.acl
      - ./data/redis/:/data
    healthcheck:
      test: redis-cli --raw ping
      interval: 10s
      timeout: 10s
      retries: 3
  postgres-db:
    image: "postgres:latest"
    container_name: postgres-db
    restart: always
    networks:
      - dcapalnetwork
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres-db
      - DATABASE_URL=postgres://postgres:postgres@postgres-db/postgres
      - SQLX_OFFLINE=true
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      networks:
        - dcapalnetwork
      ports:
        - "5020:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: dcapal@email.com
        PGADMIN_DEFAULT_PASSWORD: dcapal-user

networks:
  dcapalnetwork:
