/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * DCA-Pal APIs
 * OpenAPI spec version: 0.9.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Asset,
  GetAssetsChartParams,
  GetAssetsDataParams,
  GetPriceParams,
  ImportPortfolioBody,
  ImportPortfolioResponse,
  Price,
  SyncPortfoliosRequest,
  SyncPortfoliosResponse,
  YahooChartResponse,
  YahooSearchResponse
} from './model';

import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  TransactionFeesResponse,
  YahooChartIndicators,
  YahooChartMeta,
  YahooChartPayload
} from './model';

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type rootResponse200 = {
  data: string
  status: 200
}

export type rootResponseSuccess = (rootResponse200) & {
  headers: Headers;
};
;

export const getRootUrl = () => {




  return `/`
}

/**
 * @summary Returns the service greeting used by the root health-style endpoint.
 */
export const root = async ( options?: RequestInit): Promise<rootResponseSuccess> => {

  const res = await fetch(getRootUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: rootResponseSuccess['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as rootResponseSuccess
}





export const getRootQueryKey = () => {
    return [
    `/`
    ] as const;
    }


export const getRootQueryOptions = <TData = Awaited<ReturnType<typeof root>>, TError = globalThis.Error & { info?: unknown; status?: number }>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof root>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRootQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof root>>> = ({ signal }) => root({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof root>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RootQueryResult = NonNullable<Awaited<ReturnType<typeof root>>>
export type RootQueryError = globalThis.Error & { info?: unknown; status?: number }


export function useRoot<TData = Awaited<ReturnType<typeof root>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof root>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof root>>,
          TError,
          Awaited<ReturnType<typeof root>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRoot<TData = Awaited<ReturnType<typeof root>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof root>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof root>>,
          TError,
          Awaited<ReturnType<typeof root>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRoot<TData = Awaited<ReturnType<typeof root>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof root>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the service greeting used by the root health-style endpoint.
 */

export function useRoot<TData = Awaited<ReturnType<typeof root>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof root>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRootQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getAssetsChartResponse200 = {
  data: YahooChartResponse
  status: 200
}

export type getAssetsChartResponseSuccess = (getAssetsChartResponse200) & {
  headers: Headers;
};
;

export const getGetAssetsChartUrl = (symbol: string,
    params: GetAssetsChartParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/assets/chart/${symbol}?${stringifiedParams}` : `/assets/chart/${symbol}`
}

/**
 * @summary Proxies a historical chart request to the configured market-data provider.
 */
export const getAssetsChart = async (symbol: string,
    params: GetAssetsChartParams, options?: RequestInit): Promise<getAssetsChartResponseSuccess> => {

  const res = await fetch(getGetAssetsChartUrl(symbol,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: getAssetsChartResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAssetsChartResponseSuccess
}





export const getGetAssetsChartQueryKey = (symbol: string,
    params?: GetAssetsChartParams,) => {
    return [
    `/assets/chart/${symbol}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAssetsChartQueryOptions = <TData = Awaited<ReturnType<typeof getAssetsChart>>, TError = globalThis.Error & { info?: unknown; status?: number }>(symbol: string,
    params: GetAssetsChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsChart>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssetsChartQueryKey(symbol,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssetsChart>>> = ({ signal }) => getAssetsChart(symbol,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: symbol !== null && symbol !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssetsChart>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAssetsChartQueryResult = NonNullable<Awaited<ReturnType<typeof getAssetsChart>>>
export type GetAssetsChartQueryError = globalThis.Error & { info?: unknown; status?: number }


export function useGetAssetsChart<TData = Awaited<ReturnType<typeof getAssetsChart>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
 symbol: string,
    params: GetAssetsChartParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsChart>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetsChart>>,
          TError,
          Awaited<ReturnType<typeof getAssetsChart>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetsChart<TData = Awaited<ReturnType<typeof getAssetsChart>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
 symbol: string,
    params: GetAssetsChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsChart>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetsChart>>,
          TError,
          Awaited<ReturnType<typeof getAssetsChart>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetsChart<TData = Awaited<ReturnType<typeof getAssetsChart>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
 symbol: string,
    params: GetAssetsChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsChart>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Proxies a historical chart request to the configured market-data provider.
 */

export function useGetAssetsChart<TData = Awaited<ReturnType<typeof getAssetsChart>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
 symbol: string,
    params: GetAssetsChartParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsChart>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAssetsChartQueryOptions(symbol,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getAssetsCryptoResponse200 = {
  data: Asset[]
  status: 200
}

export type getAssetsCryptoResponseSuccess = (getAssetsCryptoResponse200) & {
  headers: Headers;
};
;

export const getGetAssetsCryptoUrl = () => {




  return `/assets/crypto`
}

/**
 * @summary Returns the cached cryptocurrency asset catalog.
 */
export const getAssetsCrypto = async ( options?: RequestInit): Promise<getAssetsCryptoResponseSuccess> => {

  const res = await fetch(getGetAssetsCryptoUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: getAssetsCryptoResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAssetsCryptoResponseSuccess
}





export const getGetAssetsCryptoQueryKey = () => {
    return [
    `/assets/crypto`
    ] as const;
    }


export const getGetAssetsCryptoQueryOptions = <TData = Awaited<ReturnType<typeof getAssetsCrypto>>, TError = globalThis.Error & { info?: unknown; status?: number }>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsCrypto>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssetsCryptoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssetsCrypto>>> = ({ signal }) => getAssetsCrypto({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssetsCrypto>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAssetsCryptoQueryResult = NonNullable<Awaited<ReturnType<typeof getAssetsCrypto>>>
export type GetAssetsCryptoQueryError = globalThis.Error & { info?: unknown; status?: number }


export function useGetAssetsCrypto<TData = Awaited<ReturnType<typeof getAssetsCrypto>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsCrypto>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetsCrypto>>,
          TError,
          Awaited<ReturnType<typeof getAssetsCrypto>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetsCrypto<TData = Awaited<ReturnType<typeof getAssetsCrypto>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsCrypto>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetsCrypto>>,
          TError,
          Awaited<ReturnType<typeof getAssetsCrypto>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetsCrypto<TData = Awaited<ReturnType<typeof getAssetsCrypto>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsCrypto>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the cached cryptocurrency asset catalog.
 */

export function useGetAssetsCrypto<TData = Awaited<ReturnType<typeof getAssetsCrypto>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsCrypto>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAssetsCryptoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getAssetsFiatResponse200 = {
  data: Asset[]
  status: 200
}

export type getAssetsFiatResponseSuccess = (getAssetsFiatResponse200) & {
  headers: Headers;
};
;

export const getGetAssetsFiatUrl = () => {




  return `/assets/fiat`
}

/**
 * @summary Returns the cached fiat asset catalog.
 */
export const getAssetsFiat = async ( options?: RequestInit): Promise<getAssetsFiatResponseSuccess> => {

  const res = await fetch(getGetAssetsFiatUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: getAssetsFiatResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAssetsFiatResponseSuccess
}





export const getGetAssetsFiatQueryKey = () => {
    return [
    `/assets/fiat`
    ] as const;
    }


export const getGetAssetsFiatQueryOptions = <TData = Awaited<ReturnType<typeof getAssetsFiat>>, TError = globalThis.Error & { info?: unknown; status?: number }>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsFiat>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssetsFiatQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssetsFiat>>> = ({ signal }) => getAssetsFiat({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssetsFiat>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAssetsFiatQueryResult = NonNullable<Awaited<ReturnType<typeof getAssetsFiat>>>
export type GetAssetsFiatQueryError = globalThis.Error & { info?: unknown; status?: number }


export function useGetAssetsFiat<TData = Awaited<ReturnType<typeof getAssetsFiat>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsFiat>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetsFiat>>,
          TError,
          Awaited<ReturnType<typeof getAssetsFiat>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetsFiat<TData = Awaited<ReturnType<typeof getAssetsFiat>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsFiat>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetsFiat>>,
          TError,
          Awaited<ReturnType<typeof getAssetsFiat>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetsFiat<TData = Awaited<ReturnType<typeof getAssetsFiat>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsFiat>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the cached fiat asset catalog.
 */

export function useGetAssetsFiat<TData = Awaited<ReturnType<typeof getAssetsFiat>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsFiat>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAssetsFiatQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getAssetsDataResponse200 = {
  data: YahooSearchResponse
  status: 200
}

export type getAssetsDataResponseSuccess = (getAssetsDataResponse200) & {
  headers: Headers;
};
;

export const getGetAssetsDataUrl = (params: GetAssetsDataParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/assets/search?${stringifiedParams}` : `/assets/search`
}

/**
 * @summary Proxies an asset-name search to the configured market-data provider.
 */
export const getAssetsData = async (params: GetAssetsDataParams, options?: RequestInit): Promise<getAssetsDataResponseSuccess> => {

  const res = await fetch(getGetAssetsDataUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: getAssetsDataResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAssetsDataResponseSuccess
}





export const getGetAssetsDataQueryKey = (params?: GetAssetsDataParams,) => {
    return [
    `/assets/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAssetsDataQueryOptions = <TData = Awaited<ReturnType<typeof getAssetsData>>, TError = globalThis.Error & { info?: unknown; status?: number }>(params: GetAssetsDataParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsData>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssetsDataQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssetsData>>> = ({ signal }) => getAssetsData(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssetsData>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAssetsDataQueryResult = NonNullable<Awaited<ReturnType<typeof getAssetsData>>>
export type GetAssetsDataQueryError = globalThis.Error & { info?: unknown; status?: number }


export function useGetAssetsData<TData = Awaited<ReturnType<typeof getAssetsData>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
 params: GetAssetsDataParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsData>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetsData>>,
          TError,
          Awaited<ReturnType<typeof getAssetsData>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetsData<TData = Awaited<ReturnType<typeof getAssetsData>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
 params: GetAssetsDataParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsData>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetsData>>,
          TError,
          Awaited<ReturnType<typeof getAssetsData>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetsData<TData = Awaited<ReturnType<typeof getAssetsData>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
 params: GetAssetsDataParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsData>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Proxies an asset-name search to the configured market-data provider.
 */

export function useGetAssetsData<TData = Awaited<ReturnType<typeof getAssetsData>>, TError = globalThis.Error & { info?: unknown; status?: number }>(
 params: GetAssetsDataParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetsData>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAssetsDataQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type importPortfolioResponse201 = {
  data: ImportPortfolioResponse
  status: 201
}

export type importPortfolioResponse400 = {
  data: void
  status: 400
}

export type importPortfolioResponseSuccess = (importPortfolioResponse201) & {
  headers: Headers;
};
export type importPortfolioResponseError = (importPortfolioResponse400) & {
  headers: Headers;
};

export const getImportPortfolioUrl = () => {




  return `/import/portfolio`
}

/**
 * @summary Validates and stores a shared portfolio payload.
 */
export const importPortfolio = async (importPortfolioBody: ImportPortfolioBody, options?: RequestInit): Promise<importPortfolioResponseSuccess> => {

  const res = await fetch(getImportPortfolioUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(importPortfolioBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: importPortfolioResponseError['data'], status?: number} = new globalThis.Error();
    const data : importPortfolioResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: importPortfolioResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as importPortfolioResponseSuccess
}





export const getImportPortfolioMutationOptions = <TError = globalThis.Error & { info?: void; status?: number },
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importPortfolio>>, TError,{data: ImportPortfolioBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof importPortfolio>>, TError,{data: ImportPortfolioBody}, TContext> => {

const mutationKey = ['importPortfolio'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof importPortfolio>>, {data: ImportPortfolioBody}> = (props) => {
          const {data} = props ?? {};

          return  importPortfolio(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ImportPortfolioMutationResult = NonNullable<Awaited<ReturnType<typeof importPortfolio>>>
    export type ImportPortfolioMutationBody = ImportPortfolioBody
    export type ImportPortfolioMutationError = globalThis.Error & { info?: void; status?: number }

    /**
 * @summary Validates and stores a shared portfolio payload.
 */
export const useImportPortfolio = <TError = globalThis.Error & { info?: void; status?: number },
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof importPortfolio>>, TError,{data: ImportPortfolioBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof importPortfolio>>,
        TError,
        {data: ImportPortfolioBody},
        TContext
      > => {
      return useMutation(getImportPortfolioMutationOptions(options), queryClient);
    }

export type getImportedPortfolioResponse200 = {
  data: unknown
  status: 200
}

export type getImportedPortfolioResponse404 = {
  data: void
  status: 404
}

export type getImportedPortfolioResponseSuccess = (getImportedPortfolioResponse200) & {
  headers: Headers;
};
export type getImportedPortfolioResponseError = (getImportedPortfolioResponse404) & {
  headers: Headers;
};

export const getGetImportedPortfolioUrl = (id: string,) => {




  return `/import/portfolio/${id}`
}

/**
 * @summary Returns a stored shared portfolio or a not-found response when it expired.
 */
export const getImportedPortfolio = async (id: string, options?: RequestInit): Promise<getImportedPortfolioResponseSuccess> => {

  const res = await fetch(getGetImportedPortfolioUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: getImportedPortfolioResponseError['data'], status?: number} = new globalThis.Error();
    const data : getImportedPortfolioResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: getImportedPortfolioResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getImportedPortfolioResponseSuccess
}





export const getGetImportedPortfolioQueryKey = (id: string,) => {
    return [
    `/import/portfolio/${id}`
    ] as const;
    }


export const getGetImportedPortfolioQueryOptions = <TData = Awaited<ReturnType<typeof getImportedPortfolio>>, TError = globalThis.Error & { info?: void; status?: number }>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportedPortfolio>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetImportedPortfolioQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getImportedPortfolio>>> = ({ signal }) => getImportedPortfolio(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getImportedPortfolio>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetImportedPortfolioQueryResult = NonNullable<Awaited<ReturnType<typeof getImportedPortfolio>>>
export type GetImportedPortfolioQueryError = globalThis.Error & { info?: void; status?: number }


export function useGetImportedPortfolio<TData = Awaited<ReturnType<typeof getImportedPortfolio>>, TError = globalThis.Error & { info?: void; status?: number }>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportedPortfolio>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getImportedPortfolio>>,
          TError,
          Awaited<ReturnType<typeof getImportedPortfolio>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImportedPortfolio<TData = Awaited<ReturnType<typeof getImportedPortfolio>>, TError = globalThis.Error & { info?: void; status?: number }>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportedPortfolio>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getImportedPortfolio>>,
          TError,
          Awaited<ReturnType<typeof getImportedPortfolio>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetImportedPortfolio<TData = Awaited<ReturnType<typeof getImportedPortfolio>>, TError = globalThis.Error & { info?: void; status?: number }>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportedPortfolio>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns a stored shared portfolio or a not-found response when it expired.
 */

export function useGetImportedPortfolio<TData = Awaited<ReturnType<typeof getImportedPortfolio>>, TError = globalThis.Error & { info?: void; status?: number }>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getImportedPortfolio>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetImportedPortfolioQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getPriceResponse200 = {
  data: Price
  status: 200
}

export type getPriceResponse404 = {
  data: void
  status: 404
}

export type getPriceResponseSuccess = (getPriceResponse200) & {
  headers: Headers;
};
export type getPriceResponseError = (getPriceResponse404) & {
  headers: Headers;
};

export const getGetPriceUrl = (asset: string,
    params: GetPriceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/price/${asset}?${stringifiedParams}` : `/price/${asset}`
}

/**
 * @summary Returns the current conversion price for a base asset and quote currency.
 */
export const getPrice = async (asset: string,
    params: GetPriceParams, options?: RequestInit): Promise<getPriceResponseSuccess> => {

  const res = await fetch(getGetPriceUrl(asset,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: getPriceResponseError['data'], status?: number} = new globalThis.Error();
    const data : getPriceResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: getPriceResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getPriceResponseSuccess
}





export const getGetPriceQueryKey = (asset: string,
    params?: GetPriceParams,) => {
    return [
    `/price/${asset}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPriceQueryOptions = <TData = Awaited<ReturnType<typeof getPrice>>, TError = globalThis.Error & { info?: void; status?: number }>(asset: string,
    params: GetPriceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrice>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPriceQueryKey(asset,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrice>>> = ({ signal }) => getPrice(asset,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: asset !== null && asset !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPrice>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPriceQueryResult = NonNullable<Awaited<ReturnType<typeof getPrice>>>
export type GetPriceQueryError = globalThis.Error & { info?: void; status?: number }


export function useGetPrice<TData = Awaited<ReturnType<typeof getPrice>>, TError = globalThis.Error & { info?: void; status?: number }>(
 asset: string,
    params: GetPriceParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrice>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrice>>,
          TError,
          Awaited<ReturnType<typeof getPrice>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrice<TData = Awaited<ReturnType<typeof getPrice>>, TError = globalThis.Error & { info?: void; status?: number }>(
 asset: string,
    params: GetPriceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrice>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrice>>,
          TError,
          Awaited<ReturnType<typeof getPrice>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrice<TData = Awaited<ReturnType<typeof getPrice>>, TError = globalThis.Error & { info?: void; status?: number }>(
 asset: string,
    params: GetPriceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrice>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the current conversion price for a base asset and quote currency.
 */

export function useGetPrice<TData = Awaited<ReturnType<typeof getPrice>>, TError = globalThis.Error & { info?: void; status?: number }>(
 asset: string,
    params: GetPriceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrice>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPriceQueryOptions(asset,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type syncPortfoliosResponse200 = {
  data: SyncPortfoliosResponse
  status: 200
}

export type syncPortfoliosResponse400 = {
  data: void
  status: 400
}

export type syncPortfoliosResponseSuccess = (syncPortfoliosResponse200) & {
  headers: Headers;
};
export type syncPortfoliosResponseError = (syncPortfoliosResponse400) & {
  headers: Headers;
};

export const getSyncPortfoliosUrl = () => {




  return `/v1/sync/portfolios`
}

/**
 * @summary Applies authenticated local portfolio changes and returns the server state.
 */
export const syncPortfolios = async (syncPortfoliosRequest: SyncPortfoliosRequest, options?: RequestInit): Promise<syncPortfoliosResponseSuccess> => {

  const res = await fetch(getSyncPortfoliosUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(syncPortfoliosRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {

    const err: globalThis.Error & {info?: syncPortfoliosResponseError['data'], status?: number} = new globalThis.Error();
    const data : syncPortfoliosResponseError['data'] = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: syncPortfoliosResponseSuccess['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as syncPortfoliosResponseSuccess
}





export const getSyncPortfoliosMutationOptions = <TError = globalThis.Error & { info?: void; status?: number },
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPortfolios>>, TError,{data: SyncPortfoliosRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof syncPortfolios>>, TError,{data: SyncPortfoliosRequest}, TContext> => {

const mutationKey = ['syncPortfolios'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof syncPortfolios>>, {data: SyncPortfoliosRequest}> = (props) => {
          const {data} = props ?? {};

          return  syncPortfolios(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SyncPortfoliosMutationResult = NonNullable<Awaited<ReturnType<typeof syncPortfolios>>>
    export type SyncPortfoliosMutationBody = SyncPortfoliosRequest
    export type SyncPortfoliosMutationError = globalThis.Error & { info?: void; status?: number }

    /**
 * @summary Applies authenticated local portfolio changes and returns the server state.
 */
export const useSyncPortfolios = <TError = globalThis.Error & { info?: void; status?: number },
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof syncPortfolios>>, TError,{data: SyncPortfoliosRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof syncPortfolios>>,
        TError,
        {data: SyncPortfoliosRequest},
        TContext
      > => {
      return useMutation(getSyncPortfoliosMutationOptions(options), queryClient);
    }


export const getRootResponseMock = (): string => (faker.word.sample())

export const getGetAssetsChartResponseYahooChartIndicatorsMock = (overrideResponse: Partial<YahooChartIndicators> = {}): YahooChartIndicators => ({...{quote: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({close: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), null]))), undefined])})), undefined])}, ...overrideResponse});

export const getGetAssetsChartResponseYahooChartMetaMock = (overrideResponse: Partial<YahooChartMeta> = {}): YahooChartMeta => ({...{currency: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])}, ...overrideResponse});

export const getGetAssetsChartResponseYahooChartPayloadMock = (overrideResponse: Partial<YahooChartPayload> = {}): YahooChartPayload => ({...{error: faker.helpers.arrayElement([{}, undefined]), result: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({indicators: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetAssetsChartResponseYahooChartIndicatorsMock()},]), undefined]), meta: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetAssetsChartResponseYahooChartMetaMock()},]), undefined])})), undefined])}, ...overrideResponse});

export const getGetAssetsChartResponseMock = (overrideResponse: Partial<Extract<YahooChartResponse, object>> = {}): YahooChartResponse => ({chart: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getGetAssetsChartResponseYahooChartPayloadMock()},]), undefined]), ...overrideResponse})

export const getGetAssetsCryptoResponseMock = (): Asset[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.helpers.arrayElement([{...{id: faker.string.alpha({length: {min: 10, max: 20}}), symbol: faker.string.alpha({length: {min: 10, max: 20}})},...{type: faker.helpers.arrayElement(['Crypto'] as const)},},{...{id: faker.string.alpha({length: {min: 10, max: 20}}), symbol: faker.string.alpha({length: {min: 10, max: 20}})},...{type: faker.helpers.arrayElement(['Fiat'] as const)},},]))))

export const getGetAssetsFiatResponseMock = (): Asset[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.helpers.arrayElement([{...{id: faker.string.alpha({length: {min: 10, max: 20}}), symbol: faker.string.alpha({length: {min: 10, max: 20}})},...{type: faker.helpers.arrayElement(['Crypto'] as const)},},{...{id: faker.string.alpha({length: {min: 10, max: 20}}), symbol: faker.string.alpha({length: {min: 10, max: 20}})},...{type: faker.helpers.arrayElement(['Fiat'] as const)},},]))))

export const getGetAssetsDataResponseMock = (overrideResponse: Partial<Extract<YahooSearchResponse, object>> = {}): YahooSearchResponse => ({quotes: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({exchange: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), longname: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), quoteType: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), shortname: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), symbol: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])})), undefined]), ...overrideResponse})

export const getImportPortfolioResponseMock = (overrideResponse: Partial<Extract<ImportPortfolioResponse, object>> = {}): ImportPortfolioResponse => ({expires_at: faker.string.alpha({length: {min: 10, max: 20}}), id: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getGetPriceResponseMock = (overrideResponse: Partial<Extract<Price, object>> = {}): Price => ({price: faker.number.float({fractionDigits: 2}), ts: faker.number.int(), ...overrideResponse})

export const getSyncPortfoliosResponseTransactionFeesResponseMock = (overrideResponse: Partial<TransactionFeesResponse> = {}): TransactionFeesResponse => ({...{feeStructure: faker.helpers.arrayElement([{type: faker.helpers.arrayElement(['zeroFee'] as const)},{feeAmount: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(['fixed'] as const)},{feeRate: faker.string.alpha({length: {min: 10, max: 20}}), maxFee: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), minFee: faker.string.alpha({length: {min: 10, max: 20}}), type: faker.helpers.arrayElement(['variable'] as const)},]), maxFeeImpact: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined])}, ...overrideResponse});

export const getSyncPortfoliosResponseMock = (overrideResponse: Partial<Extract<SyncPortfoliosResponse, object>> = {}): SyncPortfoliosResponse => ({deletedPortfolios: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.uuid())), updatedPortfolios: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({assets: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({aclass: faker.helpers.arrayElement(['EQUITY','BOND','CURRENCY','CRYPTO','COMMODITY','OTHER'] as const), averageBuyPrice: faker.string.alpha({length: {min: 10, max: 20}}), baseCcy: faker.string.alpha({length: {min: 10, max: 20}}), fees: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getSyncPortfoliosResponseTransactionFeesResponseMock()},]), undefined]), name: faker.string.alpha({length: {min: 10, max: 20}}), price: faker.string.alpha({length: {min: 10, max: 20}}), provider: faker.helpers.arrayElement(['DCAPal','YF'] as const), qty: faker.string.alpha({length: {min: 10, max: 20}}), symbol: faker.string.alpha({length: {min: 10, max: 20}}), targetWeight: faker.string.alpha({length: {min: 10, max: 20}})})), fees: faker.helpers.arrayElement([faker.helpers.arrayElement([null,{...getSyncPortfoliosResponseTransactionFeesResponseMock()},]), undefined]), id: faker.string.uuid(), lastUpdatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', name: faker.string.alpha({length: {min: 10, max: 20}}), quoteCcy: faker.string.alpha({length: {min: 10, max: 20}})})), ...overrideResponse})


export const getRootMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.get('*/', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {

  const resolvedBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRootResponseMock();
    const textBody = typeof resolvedBody === 'string' ? resolvedBody : JSON.stringify(resolvedBody ?? null);
    return HttpResponse.text(textBody,
      { status: 200
      })
  }, options)
}

export const getGetAssetsChartMockHandler = (overrideResponse?: YahooChartResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<YahooChartResponse> | YahooChartResponse), options?: RequestHandlerOptions) => {
  return http.get('*/assets/chart/:symbol', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAssetsChartResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetAssetsCryptoMockHandler = (overrideResponse?: Asset[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Asset[]> | Asset[]), options?: RequestHandlerOptions) => {
  return http.get('*/assets/crypto', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAssetsCryptoResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetAssetsFiatMockHandler = (overrideResponse?: Asset[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Asset[]> | Asset[]), options?: RequestHandlerOptions) => {
  return http.get('*/assets/fiat', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAssetsFiatResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetAssetsDataMockHandler = (overrideResponse?: YahooSearchResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<YahooSearchResponse> | YahooSearchResponse), options?: RequestHandlerOptions) => {
  return http.get('*/assets/search', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAssetsDataResponseMock(),
      { status: 200
      })
  }, options)
}

export const getImportPortfolioMockHandler = (overrideResponse?: ImportPortfolioResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<ImportPortfolioResponse> | ImportPortfolioResponse), options?: RequestHandlerOptions) => {
  return http.post('*/import/portfolio', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getImportPortfolioResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetImportedPortfolioMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.get('*/import/portfolio/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getGetPriceMockHandler = (overrideResponse?: Price | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Price> | Price), options?: RequestHandlerOptions) => {
  return http.get('*/price/:asset', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPriceResponseMock(),
      { status: 200
      })
  }, options)
}

export const getSyncPortfoliosMockHandler = (overrideResponse?: SyncPortfoliosResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<SyncPortfoliosResponse> | SyncPortfoliosResponse), options?: RequestHandlerOptions) => {
  return http.post('*/v1/sync/portfolios', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSyncPortfoliosResponseMock(),
      { status: 200
      })
  }, options)
}
export const getDCAPalAPIsMock = () => [
  getRootMockHandler(),
  getGetAssetsChartMockHandler(),
  getGetAssetsCryptoMockHandler(),
  getGetAssetsFiatMockHandler(),
  getGetAssetsDataMockHandler(),
  getImportPortfolioMockHandler(),
  getGetImportedPortfolioMockHandler(),
  getGetPriceMockHandler(),
  getSyncPortfoliosMockHandler()
]
