-- Custom types
create type public.role_status as enum ('active', 'inactive');
create type public.app_role as enum ('admin', 'authenticated');
create type public.risk_tolerance as enum ('low', 'medium', 'high');
create type public.data_source as enum ('yahoo');
create type public.investment_mode as enum ('standard', 'expert');
create type public.investment_goal as enum ('retirement', 'education', 'wealth_building', 'other');
create type public.asset_type as enum ('etf', 'stock', 'bond', 'crypto', 'other');

-- USERS
create table public.users
(
    id         uuid references auth.users             not null primary key, -- UUID from auth.users
    first_name text                                   not null,
    last_name  text,
    email      text                                   not null unique,
    birthdate  date                                   not null,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

-- ROLES
create table public.roles
(
    id         bigint generated by default as identity primary key,
    name       app_role                                  not null,
    status     role_status              default 'active' not null,
    created_at timestamp with time zone default now()    not null,
    updated_at timestamp with time zone default now()    not null
);

-- USER ROLES
create table public.user_roles
(
    id         bigint generated by default as identity primary key,
    user_id    uuid references public.users on delete cascade not null,
    role_id    bigint references public.roles                 not null,
    created_at timestamp with time zone default now()         not null,
    updated_at timestamp with time zone default now()         not null,
    unique (user_id, role_id)
);

-- PERMISSIONS
create table public.permissions
(
    id         bigint generated by default as identity primary key,
    name       text                                   not null unique,
    created_at timestamp with time zone default now() not null,
    updated_at timestamp with time zone default now() not null
);

-- ROLE PERMISSIONS
create table public.role_permissions
(
    id            bigint generated by default as identity primary key,
    role_id       bigint references public.roles         not null,
    permission_id bigint references public.permissions   not null,
    created_at    timestamp with time zone default now() not null,
    updated_at    timestamp with time zone default now() not null,
    unique (role_id, permission_id)
);

-- INSTRUMENTS

create table public.instruments
(
    id          uuid primary key         default gen_random_uuid(),
    symbol      text                                   not null unique,
    name        text                                   not null,
    exchange    text                                   not null,
    asset_type  asset_type                             not null,
    data_source data_source                            not null,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null
);

-- INSTRUMENT PRICES
create table public.instrument_prices
(
    id            uuid primary key         default gen_random_uuid(),
    instrument_id uuid references public.instruments     not null,
    eod_price     numeric(20, 10)                        not null,
    date          date                                   not null,
    created_at    timestamp with time zone default now() not null,
    updated_at    timestamp with time zone default now() not null
);

-- PORTFOLIOS
create table public.portfolios
(
    id          uuid primary key         default gen_random_uuid(),
    user_id     uuid references public.users           not null,
    name        text                                   not null,
    description text,
    created_at  timestamp with time zone default now() not null,
    updated_at  timestamp with time zone default now() not null
);

-- HOLDINGS
create table public.holdings
(
    id            uuid primary key         default gen_random_uuid(),
    portfolio     uuid references public.portfolios      not null,
    instrument_id uuid references public.instruments     not null,
    symbol        text                                   not null,
    quantity      numeric(20, 10)                        not null,
    created_at    timestamp with time zone default now() not null,
    updated_at    timestamp with time zone default now() not null
);

-- INVESTMENTS_PREFERENCES
create table public.investment_preferences
(
    id                 uuid primary key         default gen_random_uuid(),
    user_id            uuid references public.users           not null,
    risk_tolerance     risk_tolerance                         not null,
    investment_horizon int                                    not null,
    investment_mode    investment_mode                        not null,
    investment_goal    investment_goal                        not null,
    ai_enabled         boolean                                not null,
    created_at         timestamp with time zone default now() not null,
    updated_at         timestamp with time zone default now() not null
);
