name: Publish (Dev)

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [dev]

env:
  CARGO_TERM_COLOR: always
  DOCKER_REPO: leonardoarcari/dcapal
  PUBLISH_REF: ${{ github.event.workflow_run.head_branch }}  

jobs:
  extract-tag-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.PUBLISH_REF }}
      - name: Extract tag version 
        run: |
          echo "$PUBLISH_REF"
          echo "RELEASE_VERSION=${PUBLISH_REF#refs/*/}" >> $GITHUB_ENV
      - name: Echo tag version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

  build-publish-docker-image:
    runs-on: ubuntu-22.04
    needs: [extract-tag-version]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.PUBLISH_REF }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKER_REPO }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dcapal-backend/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
